/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InterviewRoleIdRouteImport } from './routes/interview.$roleId'
import { Route as ReportRoleIdRouteImport } from './routes/report.$roleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoleIdRoute = InterviewRoleIdRouteImport.update({
  id: '/interview/$roleId',
  path: '/interview/$roleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoleIdRoute = ReportRoleIdRouteImport.update({
  id: '/report/$roleId',
  path: '/report/$roleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/interview/$roleId': typeof InterviewRoleIdRoute
  '/report/$roleId': typeof ReportRoleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/interview/$roleId': typeof InterviewRoleIdRoute
  '/report/$roleId': typeof ReportRoleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/interview/$roleId': typeof InterviewRoleIdRoute
  '/report/$roleId': typeof ReportRoleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/interview/$roleId' | '/report/$roleId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/interview/$roleId' | '/report/$roleId'
  id: '__root__' | '/' | '/interview/$roleId' | '/report/$roleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InterviewRoleIdRoute: typeof InterviewRoleIdRoute
  ReportRoleIdRoute: typeof ReportRoleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/$roleId': {
      id: '/interview/$roleId'
      path: '/interview/$roleId'
      fullPath: '/interview/$roleId'
      preLoaderRoute: typeof InterviewRoleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$roleId': {
      id: '/report/$roleId'
      path: '/report/$roleId'
      fullPath: '/report/$roleId'
      preLoaderRoute: typeof ReportRoleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InterviewRoleIdRoute: InterviewRoleIdRoute,
  ReportRoleIdRoute: ReportRoleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
